### ISSUE TITLE
This is a cool idea!

### ISSUE THREAD

**Issue by dgolant** [newswim/article-archive#1]
I found this by searching my name (was looking for a ticket I opened on another account) and I love this concept!

**Comment by newswim** [comment]
Thanks! It helps a lot when I can't find an interesting article that I stumbled upon.

There's more that I could do for sure, I'm particularly inspired by people like Una Kravets who are open sourcing more of their life goals and interests. See her fantastic article:

https://una.im/personal-goals-guide

**Comment by dgolant** [comment]
I'll check it out. I stumbled on it by searching my name on Github. If you ever have trouble managing your reading list, feel free to check out my project linkmelater.win . I am currently testing it with a limited set of users so it's still a little buggy.
